# Site settings
title: undefined
header-img: img/home-bg.png
email: maryfossbender@gmail.com
copyright_name: fossbender
description: > # this means to ignore newlines until "baseurl:"
  error
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: maryfossbender
github_username:  fossbender
learn_profile: fossbender
email_username: maryfossbender@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
